### ISSUE TITLE
Userfield at company

### ISSUE THREAD

**Issue by Kruki** [2BAD/bitrix#13]
Hi,
i needed to create a company and set data for a userfield. This is possible for deals, but not for companies.

I fixed this issue locally by adding the following line to the _Company interface_ in _entities.d.ts_.

`readonly [key: string]: string | ReadonlyArray<MultiField> | null;`

I have to tell you, i am really than thankfull that you created this project. This is definitly the easiest way to work with the bitrix "REST" API. (I think no one of the developers of bitrix ever heared what REST really is, when i look at their crappy API)

**Comment by ArmorDarks** [comment]
Hi there! Thanks for the feedback ❤️ 

Hm, seems that the Company signature already [includes that index](https://studio.restream.io/?new-layouts)
