### ISSUE TITLE
crm.livefeedmessage.add

### ISSUE THREAD

**Issue by hydraqt** [2BAD/bitrix#34]
crm.livefeedmessage.add is there any way to make it work?

I'm trying to enter an activity when I make a change to a lead but it won't let me use it.

![image](https://user-images.githubusercontent.com/112430809/189553576-95704f35-90de-4129-8062-23611e2bf1bd.png)

**Comment by mrhyde** [comment]
Could you please provide more information about the issue? Are you getting any errors?

**Comment by hydraqt** [comment]
I don't have any errors, I'm asking for help to be able to implement sending a status from the api that an update was made
