### ISSUE TITLE
Error in batch response

### ISSUE THREAD

**Issue by PauloMolarinhoMattos** [2BAD/bitrix#50]
In the batch response, why not return the full object? with erros and result?.

by doind bitrix.batch, if there is an error in the array, it will throw error and the error is just a string "Error: [batch] failed to process. Received errors in 1 commands:
[object Object]"

this is a big problem, cause, after the batch, how can i know which commans have worked and which didnt? 

I would like to, after the batch, know the commands that worked and those that didnt

**Comment by mrhyde** [comment]
Could you provide a sample of the code that you are trying to run?
